name: Python application

on:
  push:
    branches:
      - main   # alebo iná vetva, ktorú používate na deploy
  workflow_dispatch:   # Umožňuje manuálne spustenie workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Zmeniť na verziu Pythonu, ktorú používaš

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest
